<html>
	<head>
  	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="http://dev.junaio.com/arel/js/arel.js"></script>
    <script type="text/javascript" src="logic_LBS9.js"></script>
    <link href="style.css" rel="stylesheet" type="text/css" />
    <title>Conoce Tu USB</title>

		<script>
			var categorias = new Array();

			$(document).ready(function() {
		  	hideAll();

		  	$("#filterButton").click(function() {
   		  	hideAll();
		    	$(".dropdown").show();
		  	});

		  	$("#searchButton").click(function() {
		    	hideAll();
		    	$(".step").show();
		  	});

		  	$("#addButton").click(function() {
		    	hideAll();
		    	$("#addPOI").show();
		  	});

		  	$("#deleteButton").click(function() {
		    	hideAll();
		    	$("#deletePOI").show();
		  	});

		  	$(".text").click(function() {
		    	$("#content").text("Texto:");
		      //$("#inputContent").attr("type","text");
		      $("#multimediaContent").show();
		  	});

		  	$(".link").click(function(){
        	$("#content").text("Enlace:");
		    	//$("#inputContent").attr("type","url");
		    	$("#multimediaContent").show();
		  	});

				$(".categoria").click(function(){
        	categorias.push($(this).val());
		  	});

		  	$("#addMultimediaButton").click(function() {
		    	hideAll();
		    	$("#addMultimedia").show();
		  	});

		  	$(".textMulti").click(function() {
		  		 $("#multimediaPOI").show();
					$("#contenidoMultimediaEnlace").hide();
		      $("#contenidoMultimedia").show();

		     
		  	});

		  	$(".linkMulti").click(function() {
		  		 $("#multimediaPOI").show();
					$("#contenidoMultimedia").hide();
		       $("#contenidoMultimediaEnlace").show();
		  
		  	});
		  	$(".cancel").click(function()
		  	{
					hideAll();
				//	$(".filterbuttonArea a.filterButton").click();
				$(".filterOptionsInner").show();
					
		  	})



			});

			function hideAll() {
				$("#addPOI").hide();
				$("#deletePOI").hide();
				$(".dropdown").hide();
				$(".step").hide();
				$("#multimediaContent").hide();
				$("#addMultimedia").hide();
				$("#multimediaPOI").hide();
				$("#contenidoMultimedia").hide();
				$("#contenidoMultimediaEnlace").hide();
			};
		</script>
	</head>
	<?php
		include ("../BD.php");
		include ("../Categoria.php");
	?>
	<body>
		<div class="filterOptions">
			<div class="filterbuttonArea">	
				<a href="#" class="filterButton">Menu</a>
				<img src="../resources/miniUSB.png" width="32" height="30" style="padding-left: 4px">
			</div>
			<div class="filterOptionsInner">
				<div class="dropdown form">
					<div class="label">Filtrado por: Categoria</div>
					<select id="filter">
						<option value = "" > Escoge una </option>
						<option value="Todas" > Todas </option>
						<?php
							$bd = new BD();
							$categoriaArray = array();
							$resultSet = $bd->consultarElem(new Categoria());
							while ($data = pg_fetch_object($resultSet)) {
								$categoria = new Categoria();
								$categoria->setNombre($data->nombre);
								array_push($categoriaArray,$categoria);
							}
							foreach ($categoriaArray as $categoria) { ?>
								<option value=<?php echo $categoria->getNombre(); ?> > <?php echo $categoria->getNombre(); ?></option>
							<?php }
						?>
					</select> 
						<button class="cancel button" >Cancelar</button>
				</div>
				<div class="step form">
					<form>
						<div class="label">Buscar:</div><input type="text" id="searchlocal" autocorrect="off" autocapitalize="off"/>		
					</form>
				<button class="cancel button" >Cancelar</button>		
				</div>
				<div id="addPOI" class="scroll form">
					Nombre: <input id="nombre" type="text" name="nombre"><br>
					Descripcion: <input id="descripcion" type="text" name="descripcion">
					Multimedia: </br>
					<input class="text" type="radio" name="multimedia" value="texto">Texto
					<input class="link" type="radio" name="multimedia" value="Imagen">Imagen
					<input class="link" type="radio" name="multimedia" value="Sonido">Sonido
					<input class="link" type="radio" name="multimedia" value="Video">Video<br>
					<div id="multimediaContent">
						<p id ="content">Texto:</p><input id="inputContent" type="text" name="contenido">
					</div>
					Categorias: </br>
					
					<?php
						$bd = new BD();
						$categoriaArray = array();
						$resultSet = $bd->consultarElem(new Categoria());
						while ($data = pg_fetch_object($resultSet)) {
							$categoria = new Categoria();
						  $categoria->setNombre($data->nombre);
						  array_push($categoriaArray,$categoria);
						}
						foreach ($categoriaArray as $categoria) { ?>
							<input class="categoria" type="checkbox" name="categoria" value=<?php echo $categoria->getNombre(); ?> >
							<?php echo $categoria->getNombre(); ?><br>
						<?php }
					?>
					<button id="create" class="button green" >Crear</button>
					<button class="cancel button" >Cancelar</button>
				</div>

				<div id="deletePOI" class="form">
					<select id="delete_poi">
						<option value="" > Escoge un poi </option>
						<?php
							$bd = new BD();
							$resultSet = $bd->consultarMisPois("admin");
							while ($data = pg_fetch_object($resultSet)) { ?>
								<option value=<?php echo $data->id; ?> > <?php echo $data->nombre; ?></option>
							<?php }
						?>
					</select>
					<button id="delete" class= "button red" >Eliminar</button>
					<button class="cancel button" >Cancelar</button>
				</div>

				<div id="addMultimedia" class ="form">
					<select id="poi">
						<option value="" > Escoge un poi </option>
						<?php
							$bd = new BD();
							$resultSet = $bd->consultarMisPois("admin");
							while ($data = pg_fetch_object($resultSet)) { ?>
								<option value=<?php echo $data->id; ?> > <?php echo $data->nombre; ?></option>
							<?php }
						?>
					</select>
					<div id="menuMultimedia">
						<input class="textMulti" type="radio" name="tipo" value="texto">Texto
						<input class="linkMulti" type="radio" name="tipo" value="Imagen">Imagen
						<input class="linkMulti" type="radio" name="tipo" value="Sonido">Sonido
						<input class="linkMulti" type="radio" name="tipo" value="Video">Video<br>
						<div id="multimediaPOI">
							<p id ="contenidoMultimedia">Texto:</p>
							<p id ="contenidoMultimediaEnlace">Enlace:</p>
							<input id="contenidoMultimediaPOI" type="text">
						</div>
					</div>

					<button id="addMulti" class ="button green">Agregar</button>
					<button class="cancel button" >Cancelar</button>
				</div>

				<br>
				<div id="buttonOptions" align="center">
					<button id="filterButton" class ="button purple">Filtrar</button>
					<button id="searchButton" class ="button ">Buscar</button>
					<button id="addButton" class="button green">Agregar POI</button>
					<button id="deleteButton" class ="button red">Eliminar POI</button>
					<button id="addMultimediaButton" class ="button blue">Agregar Multimedia</button>
				</div>
			</div>			
		</div>		

	</body>            
</html>
