<html>
	<head>
  	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="http://dev.junaio.com/arel/js/arel.js"></script>
    <script type="text/javascript" src="logic_LBS9.js"></script>
    <link href="style.css" rel="stylesheet" type="text/css" />
    <title>Conoce Tu USB</title>

		<script>
			var categorias = new Array();

			$(document).ready(function() {
		  	hideAll();

		  	$("#filterButton").click(function() {
   		  	hideAll();
		    	$(".dropdown").show();
		  	});

		  	$("#searchButton").click(function() {
		    	hideAll();
		    	$(".step").show();
		  	});

		  	$("#addButton").click(function() {
		    	hideAll();
		    	$("#addPOI").show();
		  	});

		  	$("#deleteButton").click(function() {
		    	hideAll();
		    	$("#deletePOI").show();
		  	});

		  	$(".text").click(function() {
		    	$("#content").text("Texto:");
		      //$("#inputContent").attr("type","text");
		      $("#multimediaContent").show();
		  	});

		  	$(".link").click(function(){
        	$("#content").text("Enlace:");
		    	//$("#inputContent").attr("type","url");
		    	$("#multimediaContent").show();
		  	});

				$(".categoria").click(function(){
        	categorias.push($(this).val());
		  	});
			});

			function hideAll() {
				$("#addPOI").hide();
				$("#deletePOI").hide();
				$(".dropdown").hide();
				$(".step").hide();
				$("#multimediaContent").hide();
			};
		</script>
	</head>
	<?php
		include ("../BD.php");
		include ("../Categoria.php");
	?>
	<body>
		<div class="filteroptions">
			<div class="filterbuttonArea">	
				<a href="#" class="filterButton">Filter</a>
			</div>
			<div class="filterOptionsInner">
				<div class="dropdown">
					<div class="label">Filter (Server):</div>
					<select id="filter">
						<option value="" > Escoge una categoria </option>
						<?php
							$bd = new BD();
							$categoriaArray = array();
							$resultSet = $bd->consultarElem(new Categoria());
							while ($data = pg_fetch_object($resultSet)) {
								$categoria = new Categoria();
								$categoria->setNombre($data->nombre);
								array_push($categoriaArray,$categoria);
							}
							foreach ($categoriaArray as $categoria) { ?>
								<option value=<?php echo $categoria->getNombre(); ?> > <?php echo $categoria->getNombre(); ?></option>
							<?php }
						?>
					</select> 
				</div>
				<div class="step">
					<form>
						<div class="label">Search (Locally):</div><input type="text" id="searchlocal" autocorrect="off" autocapitalize="off"/>				
					</form>
				</div>
				<div id="addPOI">
					Nombre: <input id="nombre" type="text" name="nombre"><br>
					Descripcion: <input id="descripcion" type="text" name="descripcion">
					Multimedia: </br>
					<input class="text" type="radio" name="multimedia" value="Texto">Texto
					<input class="link" type="radio" name="multimedia" value="Imagen">Imagen
					<input class="link" type="radio" name="multimedia" value="Sonido">Sonido
					<input class="link" type="radio" name="multimedia" value="Video">Video<br>
					<div id="multimediaContent">
						<p id ="content">Texto:</p><input id="inputContent" type="text" name="contenido">
					</div>
					Categorias: </br>
					
					<?php
						$bd = new BD();
						$categoriaArray = array();
						$resultSet = $bd->consultarElem(new Categoria());
						while ($data = pg_fetch_object($resultSet)) {
							$categoria = new Categoria();
						  $categoria->setNombre($data->nombre);
						  array_push($categoriaArray,$categoria);
						}
						foreach ($categoriaArray as $categoria) { ?>
							<input class="categoria" type="checkbox" name="categoria" value=<?php echo $categoria->getNombre(); ?> >
							<?php echo $categoria->getNombre(); ?><br>
						<?php }
					?>
					<button id="create" >Crear</button>
				</div>

				<div id="deletePOI">
					<select id="delete_poi">
						<option value="" > Escoge un poi </option>
						<?php
							$bd = new BD();
							$resultSet = $bd->consultarMisPois("admin");
							while ($data = pg_fetch_object($resultSet)) { ?>
								<option value=<?php echo $data->id; ?> > <?php echo $data->nombre; ?></option>
							<?php }
						?>
					</select>
					<button id="delete" >Eliminar</button>
				</div>

				<div>
				</div>

				<br>
				<div id="buttonOptions" align="center">
					<button id="filterButton">Filtrar</button>
					<button id="searchButton">Buscar</button>
					<button id="addButton">Agregar POI</button>
					<button id="deleteButton">Eliminar POI</button>
					<button id="addMultimediaButton">Agregar Multimedia</button>
				</div>
			</div>			
		</div>		

	</body>            
</html>
